### PR TITLE
Functional tests login jobs

### PR DESCRIPTION
**Pull request by ilyassjaatit**
Test login and jobviewset.

### CODE REVIEW

**Comment by manjurulhoque** [comment]
Are you sure you want to merge your changes? because I can't see any proper explanation of the PR description.

**Comment by ilyassjaatit** [comment]
Sorry, I got confused from repository

**Comment by manjurulhoque** [comment]
> Sorry, I got confused from repository

What do I need to do?

**Comment by ilyassjaatit** [comment]
Remove pull request.  
Thank you and sorry for the inconvenience.

**Pull request closed without merging**
